### PR TITLE
Update gradle-wrapper.properties file to update Gradle version from 8.6 to 8.7

### PR DESCRIPTION
**Pull request by ellet0**

### CODE REVIEW

**Review by bitspittle — APPROVED** [review]
Thank you!

**Review by bitspittle — CHANGES_REQUESTED** [review]
Actually, the patch was against the wrong base. As a result, when I changed it, the GitHub UI exploded.

I don't know why GitHub is so bad at rebasing sometimes. I'll look into reuploading your commit manually against the right branch later.

**Comment by ellet0** [comment]
> Actually, the patch was against the wrong base. As a result, when I changed it, the GitHub UI exploded.
> 
> I don't know why GitHub is so bad at rebasing sometimes. I'll look into reuploading your commit manually against the right branch later.

It happened with me too, so I decided to re-commit

I forgot to use the latest version as a branch like I always do

**Comment by bitspittle** [comment]
FYI this ended up getting done by another member of the Kobweb community, so closing this PR.

**Pull request closed without merging**
