### PR TITLE
Update font-awesome version from 6.2.0 to 6.5.1

### PR DESCRIPTION
**Pull request by ellet0**

### CODE REVIEW

**Comment by bitspittle** [comment]
Ah updating icons is more than just changing the version. The harder part is updating https://github.com/varabyte/kobweb/blob/main/frontend/silk-icons-fa/fa-icon-list.txt (as discussed in [the README](https://github.com/varabyte/kobweb/blob/main/frontend/silk-icons-fa/README.md))

**Comment by ellet0** [comment]
> Ah updating icons is more than just changing the version. The harder part is updating https://github.com/varabyte/kobweb/blob/main/frontend/silk-icons-fa/fa-icon-list.txt (as discussed in [the README](https://github.com/varabyte/kobweb/blob/main/frontend/silk-icons-fa/README.md))
> 
> 

Yes, I know, I will do it tomorrow

**Comment by NelsonHoang** [comment]
FYI, font-awesome version 6.5.2 is out. Looking forward to this update to use the Threads icon 🙂

**Comment by bitspittle** [comment]
Closing this pull request due to inactivity; Created https://github.com/varabyte/kobweb/pull/506 instead which will go in shortly to handle the 6.5.2 upgrade (just need to do a bit of sanity checking to make sure I didn't accidentally regress any icons).

threads-icon

**Pull request closed without merging**
